version = 0.1

[default.global.parameters]
stack_name = "smart-ride"
resolve_s3 = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
region = "us-east-1"

[default.sync.parameters]
watch = true
dependency_layer = false
